general:
  host: 192.168.0.140

  name: sildymas

  # how long it takes for acctuator to warm up in secs
  acctuator_warmup_time: 180

  # how long it takes for pump to stop working in secs
  heater_pump_stop_time: 600

  # ignore zone config and expect this temperature when enabled
  constant_temperature_expected: 18.0

  # min value for pwm pin in percent
  min_pwm_state: 30

  # if the temperature difference is less then min_temperature_diff_for_pwm use min_pwm_state
  min_temperature_diff_for_pwm: 0.5

  # when temperature reaches its expected value wait for it to drop temperature_drop_wait to turn acctuator back on
  temperature_drop_wait: 0.7

  heater_control_pin: 30
  heater_control_name: main_control

controls:
  main_control: 
    control_pin: 30
    zones:
      salionas:
        times:
          - start: 4:00
            end: 21:00
            expected_temperature: 21.0
        sensor_pin: 2
        control_pin: 4
      virtuve:
        times:
          - start: 4:00
            end: 21:00
            expected_temperature: 21.0
        sensor_pin: 2
        control_pin: 3
      sveciu:
        times:
          - start: 6:00
            end: 9:00
            expected_temperature: 20.5
        sensor_pin: 2
        control_pin: 5
      toletas:
        times:
          - start: 5:00
            end: 21:00
            expected_temperature: 20.5
        sensor_pin: 2
        control_pin: 6
      tamburas:
        times:
          - start: 5:00
            end: 7:00
            expected_temperature: 21.0
        sensor_pin: 2
        control_pin: 35
      katiline:
        times:
          - start: 4:00
            end: 6:00
            expected_temperature: 18.0
        sensor_pin: 2
        control_pin: 34

  slave_control:
    zones:
      miegamasis:
        times:
          - start: 2:00
            end: 23:00
            expected_temperature: 20.5
        control_pin: 10
        sensor_pin: 2
      vaiku:
        times:
          - start: 2:00
            end: 23:00
            expected_temperature: 20.5
        control_pin: 9
        sensor_pin: 2
      darbo:
        times:
          - start: 4:00
            end: 18:00
            expected_temperature: 20.5
        control_pin: 6
        sensor_pin: 2
      vonia:
        times:
          - start: 3:00
            end: 6:00
            expected_temperature: 22.0
          - start: 5:00
            end: 23:00
            expected_temperature: 21.0
        control_pin: 5
        sensor_pin: 2
      rubine:
        times:
          - start: 6:00
            end: 18:00
            expected_temperature: 20.5
        control_pin: 7
        sensor_pin: 2
